import { Platform, StyleSheet } from "react-native";
import { normalize } from "../../../shared/helpers";
import { design, labels, palette, semantic } from "../../../shared/constants/colors";
import { FONT } from "../../../shared/constants/fonts";

export const _styles = (isDarkMode: boolean) => StyleSheet.create({
    container: {
        backgroundColor: isDarkMode ? semantic.fill.f01 : '#FFFFFF',
    },
    scrollContent: {
        paddingBottom: normalize(180),
    },
    containerImage: {
        width: '100%',
        height: normalize(350),
        backgroundColor: isDarkMode ? semantic.fill.f02 : '#F8F9FA',
        justifyContent: 'center',
        alignItems: 'center',
        borderBottomLeftRadius: normalize(30),
        borderBottomRightRadius: normalize(30),
        overflow: 'hidden',
    },
    image: {
        width: '90%',
        height: '90%',
    },
    infoContainer: {
        paddingHorizontal: normalize(24),
        paddingTop: normalize(20),
    },
    headerRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
    },
    containerName: {
        flex: 1,
        marginRight: normalize(10),
    },
    name: {
        fontSize: normalize(22),
        fontFamily: FONT.BOLD,
        color: isDarkMode ? semantic.text.white : '#1A1D1E',
        lineHeight: normalize(28),
    },
    tagContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: normalize(12),
        gap: normalize(8),
    },
    badge: {
        paddingHorizontal: normalize(10),
        paddingVertical: normalize(4),
        borderRadius: normalize(8),
        flexDirection: 'row',
        alignItems: 'center',
    },
    sachetBadge: {
        backgroundColor: '#FFF3E0',
    },
    sachetText: {
        color: '#E65100',
        fontSize: normalize(10),
        fontFamily: FONT.MEDIUM,
    },
    quantityBadge: {
        backgroundColor: '#E8F5E9',
    },
    quantityText: {
        color: '#2E7D32',
        fontSize: normalize(10),
        fontFamily: FONT.MEDIUM,
    },
    expiryBadge: {
        backgroundColor: '#F5F5F5',
    },
    expiryText: {
        color: '#616161',
        fontSize: normalize(10),
        fontFamily: FONT.MEDIUM,
    },
    classificationBadge: {
        backgroundColor: '#E3F2FD',
    },
    classificationText: {
        color: '#1565C0',
        fontSize: normalize(10),
        fontFamily: FONT.MEDIUM,
    },
    priceSection: {
        marginTop: normalize(20),
        flexDirection: 'row',
        alignItems: 'baseline',
    },
    total: {
        fontSize: normalize(28),
        fontFamily: FONT.BOLD,
        color: semantic.alert.danger.d500,
    },
    special: {
        fontSize: normalize(16),
        color: '#9E9E9E',
        textDecorationLine: "line-through",
        marginLeft: normalize(10),
        fontFamily: FONT.MEDIUM,
    },
    doorStepContainer: {
        marginTop: normalize(8),
        backgroundColor: isDarkMode ? semantic.fill.f02 : '#FCE4E4',
        padding: normalize(10),
        borderRadius: normalize(10),
        borderLeftWidth: 4,
        borderLeftColor: semantic.alert.danger.d500,
    },
    doorStepText: {
        fontSize: normalize(11),
        color: semantic.alert.danger.d500,
        fontFamily: FONT.MEDIUM,
    },
    customPriceContainer: {
        marginTop: normalize(12),
        padding: normalize(12),
        backgroundColor: '#E8F5E9',
        borderRadius: normalize(12),
        borderWidth: 1,
        borderColor: '#C8E6C9',
    },
    customPriceText: {
        fontSize: normalize(12),
        color: '#2E7D32',
        fontFamily: FONT.BOLD,
    },
    separator: {
        height: 1,
        backgroundColor: '#F0F0F0',
        marginVertical: normalize(24),
    },
    descriptionContainer: {
        marginBottom: normalize(20),
    },
    descriptionTitle: {
        fontSize: normalize(18),
        fontFamily: FONT.BOLD,
        color: isDarkMode ? semantic.text.white : '#1A1D1E',
        marginBottom: normalize(10),
    },
    description: {
        fontSize: normalize(14),
        lineHeight: normalize(22),
        color: isDarkMode ? '#BDBDBD' : '#616161',
        fontFamily: FONT.NORMAL,
    },
    footer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: isDarkMode ? semantic.fill.f01 : '#FFFFFF',
        paddingHorizontal: normalize(24),
        paddingTop: normalize(16),
        paddingBottom: Platform.OS === 'ios' ? normalize(34) : normalize(10),
        borderTopWidth: 1,
        borderTopColor: isDarkMode ? semantic.fill.f04 : '#F0F0F0',
        elevation: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
    },
    quantityRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: normalize(20),
        backgroundColor: isDarkMode ? semantic.fill.f02 : '#F8F9FA',
        padding: normalize(16),
        borderRadius: normalize(16),
        borderWidth: 1,
        borderColor: isDarkMode ? semantic.fill.f04 : '#EEE',
    },
    quantityLabel: {
        fontSize: normalize(16),
        fontFamily: FONT.BOLD,
        color: isDarkMode ? semantic.text.white : '#1A1D1E',
    },
    buttonRow: {
        flexDirection: 'row',
        gap: normalize(12),
    },
    buyNowButton: {
        flex: 1,
        shadowColor: semantic.alert.danger.d500,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 5,
    },
    addToCartButton: {
        flex: 1.2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 5,
    },
    outOfStockContainer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        zIndex: 100,
        justifyContent: 'center',
        alignItems: 'center',
    },
    outOfStockBadge: {
        backgroundColor: '#D50000',
        paddingHorizontal: normalize(24),
        paddingVertical: normalize(12),
        borderRadius: normalize(8),
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    outOfStockText: {
        color: '#FFFFFF',
        fontSize: normalize(18),
        fontFamily: FONT.BOLD,
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    wishlistButton: {
        position: 'absolute',
        top: normalize(20),
        right: normalize(20),
        zIndex: 150,
        backgroundColor: isDarkMode ? 'rgba(0,0,0,0.5)' : 'rgba(255,255,255,0.9)',
        borderRadius: normalize(25),
        width: normalize(50),
        height: normalize(50),
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 10,
        elevation: 8,
    },
    wishlistIconDetailed: {
        width: normalize(24),
        height: normalize(24),
        tintColor: '#D50000',
    },
    bundleInfo: {
        marginTop: normalize(16),
        padding: normalize(16),
        backgroundColor: 'rgba(37, 99, 235, 0.05)',
        borderRadius: normalize(16),
        borderWidth: 1,
        borderColor: 'rgba(37, 99, 235, 0.1)',
        borderStyle: 'dashed',
    },
    bundleTitle: {
        fontSize: normalize(15),
        fontFamily: FONT.BOLD,
        color: '#2563EB',
        marginBottom: normalize(8),
    },
    bundleItem: {
        fontSize: normalize(13),
        fontFamily: FONT.MEDIUM,
        color: '#334155',
        lineHeight: normalize(18),
    },
    bundleMeta: {
        fontSize: normalize(11),
        fontFamily: FONT.MEDIUM,
        color: '#64748B',
    },
    optionsContainer: {
        marginTop: normalize(20),
        gap: normalize(16),
    },
    optionGroup: {
        gap: normalize(10),
    },
    optionGroupName: {
        fontSize: normalize(16),
        fontFamily: FONT.BOLD,
        color: isDarkMode ? semantic.text.white : '#1A1D1E',
    },
    optionsList: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: normalize(10),
    },
    optionChip: {
        paddingHorizontal: normalize(16),
        paddingVertical: normalize(8),
        borderRadius: normalize(12),
        borderWidth: 1,
        borderColor: isDarkMode ? semantic.fill.f04 : '#EEE',
        backgroundColor: isDarkMode ? semantic.fill.f02 : '#F8F9FA',
    },
    optionChipSelected: {
        borderColor: semantic.alert.danger.d500,
        backgroundColor: isDarkMode ? 'rgba(213, 0, 0, 0.1)' : '#FCE4E4',
    },
    optionChipText: {
        fontSize: normalize(14),
        fontFamily: FONT.MEDIUM,
        color: isDarkMode ? '#BDBDBD' : '#616161',
    },
    optionChipTextSelected: {
        color: semantic.alert.danger.d500,
        fontFamily: FONT.BOLD,
    },
    optionPriceAdjustment: {
        fontSize: normalize(11),
        fontFamily: FONT.BOLD,
        marginLeft: normalize(4),
    },
})
