import { Platform, StyleSheet } from "react-native";
import { normalize } from "../../helpers";
import { labels, palette, semantic } from "../../constants/colors";
import { FONT } from "@/shared/constants/fonts.ts";

export const _styles = (isDarkMode: boolean) => StyleSheet.create({
  container: {
    width: normalize(165),
    backgroundColor: isDarkMode ? semantic.fill.f01 : semantic.fill.f03,
    borderRadius: normalize(15),
    padding: normalize(8),
    margin: normalize(8),
    borderWidth: 1,
    borderColor: isDarkMode ? semantic.fill.f02 : '#f0f0f0',
    position: 'relative',
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
      },
      android: {
        elevation: 3,
      }
    }),
  },
  imageContainer: {
    width: '100%',
    height: normalize(120),
    borderRadius: normalize(12),
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: isDarkMode ? semantic.fill.f02 : '#f9f9f9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  image: {
    width: '80%',
    height: '80%',
    resizeMode: 'contain',
  },
  badgeContainer: {
    position: 'absolute',
    top: normalize(8),
    left: normalize(8),
    flexDirection: 'column',
    gap: normalize(4),
  },
  badge: {
    paddingHorizontal: normalize(6),
    paddingVertical: normalize(2),
    borderRadius: normalize(8),
  },
  badgeText: {
    color: semantic.text.white,
    fontSize: normalize(8),
    fontFamily: FONT.BOLD,
  },
  expiryBadge: {
    backgroundColor: labels.type1.background,
  },
  expiryText: {
    color: labels.type1.textColor,
  },
  quantityBadge: {
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  info: {
    marginTop: normalize(8),
    paddingHorizontal: normalize(4),
  },
  name: {
    fontFamily: FONT.MEDIUM,
    color: isDarkMode ? semantic.text.white : semantic.text.black,
    fontSize: normalize(13),
    height: normalize(35),
    marginBottom: normalize(4),
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: normalize(4),
    flexWrap: 'wrap',
  },
  price: {
    fontSize: normalize(14),
    fontFamily: FONT.SEMI_BOLD,
    color: isDarkMode ? semantic.text.white : semantic.text.black,
  },
  oldPrice: {
    fontSize: normalize(10),
    color: semantic.alert.danger.d500,
    textDecorationLine: "line-through",
    marginLeft: normalize(6),
  },
  doorStep: {
    fontSize: normalize(10),
    color: isDarkMode ? semantic.alert.success.s300 : palette.main.p500,
    marginTop: normalize(4),
    fontFamily: FONT.MEDIUM,
  },
  addToCart: {
    position: 'absolute',
    bottom: normalize(8),
    right: normalize(8),
    backgroundColor: '#D50000',
    width: normalize(30),
    height: normalize(30),
    borderRadius: normalize(15),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: semantic.text.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 4,
  },
  outOfStockContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    zIndex: 200,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: normalize(15),
  },
  outOfStockBadge: {
    backgroundColor: '#D50000',
    paddingHorizontal: normalize(12),
    paddingVertical: normalize(6),
    borderRadius: normalize(6),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  outOfStockText: {
    color: '#FFFFFF',
    fontSize: normalize(10),
    fontFamily: FONT.BOLD,
    textTransform: 'uppercase',
  },
  wishlistButton: {
    position: 'absolute',
    top: normalize(10),
    right: normalize(10),
    zIndex: 250,
    backgroundColor: isDarkMode ? 'rgba(0,0,0,0.5)' : 'rgba(255,255,255,0.8)',
    borderRadius: normalize(15),
    width: normalize(28),
    height: normalize(28),
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  wishlistIcon: {
    width: normalize(16),
    height: normalize(16),
    tintColor: '#D50000',
  },
});
