export const SET_APPLICATION_DATA = "SET_APPLICATION_DATA";
export const PAGE_ROUTER_DATA = "PAGE_ROUTER_DATA";

export const PRODUCT_DIALOG_DATA = "PRODUCT_DIALOG_DATA";

export const ENVIRONMENT = "ENVIRONMENT";

export const LAUNCH_PAGE = "LAUNCH_PAGE";

export const IMPERSONATE_DATA = "IMPERSONATE_DATA";

export const TRASHED_USER = "TRASHED_USER";

export const FIREBASE_DEVICE_KEY = "FIREBASE_DEVICE_KEY";

export const SUPERMARKET_HOMEPAGE_DATA = "SUPERMARKET_HOMEPAGE_DATE";

export const WHOLESALES_HOMEPAGE_DATA = "WHOLESALES_HOMEPAGE_DATE";
